name: Build

on:
  push:
    tags:
      - '1.*'
      - '2.*'
    branches:
  pull_request:
  workflow_dispatch:

jobs:
  build-node:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11]
        node: [17.6.0]
        architecture: [x64]
        include:
          - architecture: x64
            architecture_node: x64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: xcversion select 11.2.1 --symlink
        if: ${{ runner.os == 'macOS' }}
      - run: xcversion install-cli-tools
        if: ${{ runner.os == 'macOS' }}
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          architecture: ${{ matrix.architecture_node }}
      - run: npm -g install npm@^6.14.5
      - run: node --version
      - run: npm --version
      - run: npm install node-gyp@5.1.1 --global
      - run: npm config set msbuild_path "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe"
        if: ${{ runner.os == 'Windows' }}
      - run: npm install --build-from-source
        env:
          npm_config_arch: ${{ matrix.architecture }}
          npm_config_target_arch: ${{ matrix.architecture }}
      - run: ./node_modules/.bin/node-pre-gyp package testpackage
      - uses: actions/upload-artifact@v2
        with:
          path: build/stage/julianhille/MuhammaraJS/releases/download/**/*.gz
          name: bindings
          if-no-files-found: error
